### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by rgkirch** [Cirru/calcit-editor#120]
on windows 8
ran `npm i -g calcit-editor` and then `calcit-editor`

```
$ calcit-editor
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:424:7)
    at C:\Users\richie\AppData\Roaming\npm\node_modules\calcit-editor\dist\server.js:783:56
    at Object.<anonymous> (C:\Users\richie\AppData\Roaming\npm\node_modules\calcit-editor\dist\server.js:791:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by jiyinyiyong** [comment]
I don't have a windows for test. But on Windows, the shell env is different, `process.env.X` could be different from Unix systems.
![image](https://user-images.githubusercontent.com/449224/138022544-7aa054ae-8ead-4fe7-8d02-321a2b0fcef5.png)

**Comment by rgkirch** [comment]
Cool, it works now. Thanks!
